### ISSUE TITLE
Error on npm run build

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Web#137]
Hallo Marvin,
hast du eine Idee?

````
dapnet@funkruftxdl5ml:/opt/dapnet/Web $ nodejs -v
v9.5.0
````
````
dapnet@funkruftxdl5ml:/opt/dapnet/Web $ npm -v
5.6.0
````

``npm run build`` liefert:

````
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@5.6.0
3 info using node@v9.5.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle dapnet-web@2.1.6~prebuild: dapnet-web@2.1.6
6 info lifecycle dapnet-web@2.1.6~build: dapnet-web@2.1.6
7 verbose lifecycle dapnet-web@2.1.6~build: unsafe-perm in lifecycle true
8 verbose lifecycle dapnet-web@2.1.6~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/dapnet/Web/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle dapnet-web@2.1.6~build: CWD: /opt/dapnet/Web
10 silly lifecycle dapnet-web@2.1.6~build: Args: [ '-c', 'node build/build.js' ]
11 silly lifecycle dapnet-web@2.1.6~build: Returned: code: 1  signal: null
12 info lifecycle dapnet-web@2.1.6~build: Failed to exec build script
13 verbose stack Error: dapnet-web@2.1.6 build: `node build/build.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:160:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:160:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid dapnet-web@2.1.6
15 verbose cwd /opt/dapnet/Web
16 verbose Linux 4.9.35-v7+
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v9.5.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error dapnet-web@2.1.6 build: `node build/build.js`
22 error Exit status 1
23 error Failed at the dapnet-web@2.1.6 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
````
````
ERROR in ./src/main.js
Module build failed: SyntaxError: Error parsing /opt/dapnet/Web/node_modules/babel-preset-env/node_modules/babel-plugin-transform-async-to-generator/node_modules/babel-helper-remap-async-to-generator/node_modules/babel-traverse/node_modules/babel-code-frame/node_modules/chalk/node_modules/supports-color/package.json: Unexpected end of JSON input (While processing preset: "/opt/dapnet/Web/node_modules/babel-preset-env/lib/index.js")
    at JSON.parse (<anonymous>)
    at readPackage (module.js:133:52)
    at tryPackage (module.js:143:13)
    at Function.Module._findPath (module.js:225:20)
    at Function.Module._resolveFilename (module.js:553:25)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/dapnet/Web/node_modules/babel-preset-env/node_modules/babel-plugin-transform-async-to-generator/node_modules/babel-helper-remap-async-to-generator/node_modules/babel-traverse/node_modules/babel-code-frame/node_modules/chalk/index.js:6:21)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)

  Build failed with errors.
````

**Comment by MarvinMenzerath** [comment]
Kannst du mal das `node_modules/` Verzeichnis entfernen, ein `npm install` ausführen und danach noch einmal `npm run build` starten? Da scheint eine der Abhängigkeiten Probleme zu machen...

**Comment by dh3wr** [comment]
Vielen Dank, Marvin. Hat sich mit deinem Hinweis geklärt
